//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JooleStore_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Department
    {
        public int DepartmentId { get; set; }
        public int ManufacturerId { get; set; }
        public string DepartmentName { get; set; }
        public Nullable<int> DepartmentPhone { get; set; }
        public string DepartmentEmail { get; set; }
    
        public virtual Manufacturer Manufacturer { get; set; }
    }
}
