//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JooleStore_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPropertyValue
    {
        public int PropertyId { get; set; }
        public int ProductId { get; set; }
        public string PropertyValue { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Property Property { get; set; }
    }
}
